server:
  port: 8081

logging:
  level:
    org:
      springframework: info
    com:
      defecttracking: debug
  file:
    name: defecttrackingapi.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


